### ISSUE TITLE
TS2590: Expression produces a union type that is too complex to represent.

### ISSUE THREAD

**Issue by dbaum** [benjamn/ast-types#366]
I think tsc 3.6.3 is having trouble with the union of values in builtInTypes:

types.ts:411:5 - error TS2590: Expression produces a union type that is too complex to represent.

411     builtInTypes[name] = type;
        ~~~~~~~~~~~~~~~~~~

**Comment by SnarkBoojum** [comment]
I'm using tsc 3.7.4  and I see the same problem...

**Comment by SnarkBoojum** [comment]
Same issue with tsc 3.8.2.

**Comment by SnarkBoojum** [comment]
Is there something I can do to help pinpoint the issue and be done with it?

**Comment by SnarkBoojum** [comment]
Same issue with tsc 3.8.3.

**Comment by SnarkBoojum** [comment]
Sifting through my list of pending issues with my packages, I see I can't update ast-types in Debian because it doesn't work with recent tsc.

**Comment by SnarkBoojum** [comment]
Still no luck with ast-types 0.13.3 : doesn't work with tsc 3.8.3.

**Comment by SnarkBoojum** [comment]
Just retried with tsc 3.9.2 and ast-types 0.13.3 : same error.

**Comment by SnarkBoojum** [comment]
Same issue with tsc 3.9.7.
